---
mock_with: ':rspec'

appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.project:
  delete: true

spec/default_facts.yml:
  extra_facts:
    pe_server_version: '2016.4.5'
.rubocop.yml:
  selected_profile: off

.travis.yml:
  branches:
    - master
    - main
    - /^v\d/
