---
common:

".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
.gitpod.Dockerfile:
  unmanaged: true
.gitpod.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/pr_test.yml:
  unmanaged: true
.github/workflows/auto_release.yml:
  unmanaged: true
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: true
.travis.yml:
  delete: true
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
Rakefile:
  changelog_user: "puppetlabs"

.rubocop.yml:
  default_configs:
    "RSpec/NamedSubject":
       Enabled: False
    "Style/ClassAndModuleChildren":
       Enabled: False
    "Style/CollectionMethods":
       Enabled: False
    "Style/LineEndConcatenation":
       Enabled: False
    "Lint/AssignmentInCondition":
       Enabled: False
    "Lint/RescueException":
       Enabled: False
    "Lint/UnderscorePrefixedVariableName":
       Enabled: False
    "Lint/UselessAssignment":
       Enabled: False
    "Style/Documentation":
       Enabled: False
    "Style/GlobalVars":
       Enabled: False
    "Style/GuardClause":
       Enabled: False
    "RSpec/EmptyExampleGroup":
       Enabled: False

Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
