#!/bin/bash

set -e

# Arguments and defaults.

while [[ $1 ]]; do
  case "$1" in
    '-m'|'--metrics-dir')
      arg_metrics_dir="$2"
      ;;
    '-r'|'--retention-days')
    arg_retention_days="$2"
  esac
  shift 2
done

METRICS_OUTPUT_DIR=${arg_metrics_dir:-/opt/puppetlabs/puppet-metrics-collector}
RETENTION_DAYS=${arg_retention_days:-30}

DATETIME=$(date +%Y.%m.%d.%H.%M.%S)
OUTPUT_FILE="$(pwd)/puppet-metrics-$DATETIME.tar.gz"

cd "$METRICS_OUTPUT_DIR"
find . -type f -ctime -"$RETENTION_DAYS" -regex '\(.*gz$\|.*json$\)' > "$METRICS_OUTPUT_DIR.tmp"
tar --create --gzip --file "$OUTPUT_FILE" --files-from "$METRICS_OUTPUT_DIR.tmp" --transform "s,^,/puppet-metrics-$DATETIME/,"
rm "$METRICS_OUTPUT_DIR.tmp"

echo "Created metrics archive: ${OUTPUT_FILE}"
