#!/bin/bash

while [[ $1 ]]; do
   case "$1" in
      '-m'|'--metrics-dir')
         metrics_dir="$2"
         ;;
      '-r'|'--retention-days')
         ret_days="$2"
   esac
   shift 2
done

# Arguments and defaults.
metrics_dir="${metrics_dir:-/opt/puppetlabs/puppet-metrics-collector}"
ret_days="${ret_days:-30}"
output_file="puppet-metrics-collector-$(date +%Y.%m.%d.%H.%M.%S).tar.gz"

find "$metrics_dir" -type f -ctime -"$ret_days" -a \( -name "*json" -o -name "*gz" \) | \
   tar czf "$output_file" --transform "s,^${metrics_dir#/},puppet-metrics," --files-from - || exit 1

echo "Created metrics archive: $output_file"
