#!/bin/bash

while [[ $1 ]]; do
   case "$1" in
      '-m'|'--metrics-dir')
         metrics_dir="$2"
         ;;
      '-r'|'--retention-days')
         ret_days="$2"
   esac
   shift 2
done

# Arguments and defaults.
metrics_dir="${metrics_dir:-/opt/puppetlabs/puppet-metrics-collector/puppetserver}"
ret_days="${ret_days:-90}"
metrics_type="${metrics_dir##*/}"

# Guard against deleting or archiving other files. 
valid_paths=(puppetserver puppetdb orchestrator ace bolt activemq)
paths_regex="$(IFS='|'; echo "${valid_paths[*]}")"

# Check that the directory ends in one of the Puppet services we collect metrics for
[[ $metrics_dir =~ ${paths_regex}$ ]] || {
   echo "Invalid metrics path.  Must end in one of: $(echo -n "${valid_paths[@]}")."
   exit 1
}

# Delete files older than the retention period, in days.
find "$metrics_dir" -type f -ctime +"$ret_days" -delete

# Compress the remaining files.
find "$metrics_dir" -type f -name "*json" | tar zcf "${metrics_dir}/${metrics_type}-$(date +%Y.%m.%d.%H.%M.%S).tar.gz" --files-from -
